### ISSUE TITLE
Using with binary(16)

### ISSUE THREAD

**Issue by plandolt** [digital-craftsman-de/ids#38]
I am currently stuck with a problem I do not yet see a solution: I have database entries with binary(16) which are for now Symfony Uuid primary keys. The problem with that is, that I can't always define the "uuid" type for a doctrine query parameter to make it work. Otherwise, it will just use the string representation to query the database and won't find anything. I need to either specify the parameter type or use the binary representation of the uuid directly as the parameter value.

So i installed this library and defined the `IdType` and overrid this methods:
```php
    public function getSQLDeclaration(array $column, AbstractPlatform $platform): string
    {
        $column['length'] = 16;
        $column['fixed'] = true;

        return $platform->getBinaryTypeDeclarationSQL($column);
    }

    public function getBindingType()
    {
        return ParameterType::BINARY;
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform): ?string
    {
        if (null === $value) {
            return null;
        }

        if (is_string($value)) {
            return Uuid::fromString($value)->toBinary();
        }

        if ($value instanceof Id) {
            return Uuid::fromString((string) $value)->toBinary();
        }
    }

    public function convertToPHPValue($value, AbstractPlatform $platform): ?Id
    {
        if (null === $value) {
            return null;
        }

        return $this->getIdClass()::fromBinary($value);
    }
```

Not pretty, but does the job. Now when I use the query builder like this:
```php
    $result = $this->createQueryBuilder('a')
            ->andWhere('a.relation = :relation')
            ->setParameter('relation', $relationEntityObject)
            ->getQuery()
            ->getResult()
        ;
```

I still do not get the result as the generated query still using the string representation and not the binary (as I was expecting with the `convertToDatabaseValue` method.

Does anyone have an idea what I am missing?

**Comment by christian-kolb** [comment]
I haven't worked with the binary variant yet, so I can only think of the most obvious thing:

Do your id types, like for example `UserIdType` extend from your custom `IdType` instead of the `DigitalCraftsman\Ids\Doctrine\IdType`? 

If they do, can you use a debugger or throw in a `var_dump` and `exit` in there to see if your id type is triggered?

**Comment by christian-kolb** [comment]
Out of curiosity: What's your use case for using binary representations of the ids?

**Comment by plandolt** [comment]
For hydrating objects fetched from the database, they get mapped by `convertToPHPValue`. So the type is registered correctly.

A query with the ID as parameter and specify the type works too:
```php
    $qb = $this->createQueryBuilder('r')
            ->andWhere('r.relation = :relation')
//            ->setParameter('relation', $relationEntityObject)
            ->setParameter('relation', $relationEntityObject->getId(), 'relation_id')
        ;
```

It might be more of a doctrine issue (probably not bug but intentional behavior, or I just miss something) than with your package.

Why I use binary(16): The current database Is set up like that. So I do not need to convert all primary and foreign keys to char(36).

**Comment by plandolt** [comment]
I think I found the solution (not sure if it will cover all edge cases). Doctrine is using the `__toString()` method of the Id (not the type) to get the final value. So If I overwrite it to generate a binary it works in a query without specifying the doctrine type name:

```php
    public function __toString(): string
    {
        return Uuid::fromString($this->value)->toBinary();
    }
```

**Comment by plandolt** [comment]
Like somehow expected, that creates a lot of trouble for stuff that expects the uuid back from the `__toString` method.

**Comment by christian-kolb** [comment]
Ok that makes sense and is an implementation detail of Doctrine.
I'd caution against that for mid to long term though. A few things of the package does or will rely on the string within an id to be identical to the one that `__toString()` will produce. I don't know and can't guarantee that this won't lead to breaking issues now or in the future.

**Comment by christian-kolb** [comment]
> Like somehow expected, that creates a lot of trouble for stuff that expects the uuid back from the `__toString` method.

Ok, so you've already run into the first issues. At least my hunch was correct there. Is the conversion into char(32) a big deal?

**Comment by plandolt** [comment]
Yes, I guess that's the way it needs to be done to work in 2023. Unfortunately for the storage size and sortable capabilities that would be better with binary (or the uuid column coming in the future versions of mariadb).

Thank you for your timely response and help!

**Comment by christian-kolb** [comment]
I can just recommend switching to Postgres. I worked with MySQL/MariaDB too, and basically everything that I care about is better there 😄 Including UUID data types and working with JSON.

Best of luck with your conversion 🙂

**Comment by plandolt** [comment]
Yes I want that too, but I'm just so familiar with mysql/mariadb and am lazy :)

But do you use the UUID data type from postgres or also char(36) for IDs?

**Comment by christian-kolb** [comment]
The `IdType` uses `getGuidTypeDeclarationSQL`, which in turn is converted to for example `user_id UUID NOT NULL` 🙂
The instances where I need to compare it to strings, I just use `user_id::text`. But that basically never happens.
