### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by plandolt** [digital-craftsman-de/ids#55]

**Comment by christian-kolb** [comment]
@scuben Do you by any chance already have running Symfony 7 system? Then I'll provide the PR and you can validate it against it?

**Comment by christian-kolb** [comment]
@scuben I've added a PR to bring compatibility for Symfony 7 #56. Let me know when you gave it a spin 😉

**Comment by plandolt** [comment]
Thank you. I'll check it as soon as I have a project to upgrade that is not blocked by another dependency.

**Comment by plandolt** [comment]
I today upgraded the application to sf7 without any problems using the pr. I think it's fine to merge.

**Comment by christian-kolb** [comment]
Awesome, then I'll try to resolve the merge conflicts introduced in the meantime and publish a release by the end of the day 🙂
Thanks for your help!

**Comment by christian-kolb** [comment]
@scuben New release was just published 🙂
